export const UPDATE_TOKEN = 'UPDATE_TOKEN'
export const UPDATE_BOT = 'UPDATE_BOT'

export const DELETE_USER = 'DELETE_USER'
export const DELETE_TOKEN = 'DELETE_TOKEN'
export const DELETE_BOT = 'DELETE_BOT'

export const UPDATE_BOT_SENT = 'UPDATE_BOT_SENT'
export const UPDATE_BOT_SUCCESS = 'UPDATE_BOT_SUCCESS'
export const UPDATE_BOT_REJECTED = 'UPDATE_BOT_REJECTED'

export const FETCH_BOT_SENT = 'FETCH_BOT_SENT'
export const FETCH_BOT_SUCCESS = 'FETCH_BOT_SUCCESS'
export const FETCH_BOT_REJECTED = 'FETCH_BOT_REJECTED'

export const CREATE_BOT_SENT = 'CREATE_BOT_SENT'
export const CREATE_BOT_SUCCESS = 'CREATE_BOT_SUCCESS'
export const CREATE_BOT_REJECTED = 'CREATE_BOT_REJECTED'

export const UPDATE_USER = 'UPDATE_USER'

export const FETCH_USER_SENT = 'FETCH_USER_SENT'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_REJECTED = 'FETCH_USER_REJECTED'

export const JOIN_CHANNEL_SENT = 'JOIN_CHANNEL_SENT'
export const JOIN_CHANNEL_SUCCESS = 'JOIN_CHANNEL_SUCCESS'
export const JOIN_CHANNEL_REJECTED = 'JOIN_CHANNEL_REJECTED'

export const PART_CHANNEL_SENT = 'PART_CHANNEL_SENT'
export const PART_CHANNEL_SUCCESS = 'PART_CHANNEL_SUCCESS'
export const PART_CHANNEL_REJECTED = 'PART_CHANNEL_REJECTED'

export const FETCH_COMMANDS_SENT = 'FETCH_COMMANDS_SENT'
export const FETCH_COMMANDS_SUCCESS = 'FETCH_COMMANDS_SUCCESS'
export const FETCH_COMMANDS_REJECTED = 'FETCH_COMMANDS_REJECTED'

export const CREATE_COMMAND_SENT = 'CREATE_COMMAND_SENT'
export const CREATE_COMMAND_SUCCESS = 'CREATE_COMMAND_SUCCESS'
export const CREATE_COMMAND_REJECTED = 'CREATE_COMMAND_REJECTED'

export const DELETE_COMMANDS_SENT = 'DELETE_COMMANDS_SENT'
export const DELETE_COMMANDS_SUCCESS = 'DELETE_COMMANDS_SUCCESS'
export const DELETE_COMMANDS_REJECTED = 'DELETE_COMMANDS_REJECTED'

export const EDIT_COMMAND_SENT = 'EDIT_COMMAND_SENT'
export const EDIT_COMMAND_SUCCESS = 'EDIT_COMMAND_SUCCESS'
export const EDIT_COMMAND_REJECTED = 'EDIT_COMMAND_REJECTED'

export const FETCH_FILTERS_SENT = 'FETCH_FILTERS_SENT'
export const FETCH_FILTERS_SUCCESS = 'FETCH_FILTERS_SUCCESS'
export const FETCH_FILTERS_REJECTED = 'FETCH_FILTERS_REJECTED'
export const EDIT_FILTER_SENT = 'EDIT_FILTER_SENT'
export const EDIT_FILTER_SUCCESS = 'EDIT_FILTER_SUCCESS'
export const EDIT_FILTER_REJECTED = 'EDIT_FILTER_REJECTED'

export const FETCH_TIMERS_SENT = 'FETCH_TIMERS_SENT'
export const FETCH_TIMERS_SUCCESS = 'FETCH_TIMERS_SUCCESS'
export const FETCH_TIMERS_REJECTED = 'FETCH_TIMERS_REJECTED'

export const CREATE_TIMER_SENT = 'CREATE_TIMER_SENT'
export const CREATE_TIMER_SUCCESS = 'CREATE_TIMER_SUCCESS'
export const CREATE_TIMER_REJECTED = 'CREATE_TIMER_REJECTED'

export const DELETE_TIMERS_SENT = 'DELETE_TIMERS_SENT'
export const DELETE_TIMERS_SUCCESS = 'DELETE_TIMERS_SUCCESS'
export const DELETE_TIMERS_REJECTED = 'DELETE_TIMERS_REJECTED'

export const EDIT_TIMER_SENT = 'EDIT_TIMER_SENT'
export const EDIT_TIMER_SUCCESS = 'EDIT_TIMER_SUCCESS'
export const EDIT_TIMER_REJECTED = 'EDIT_TIMER_REJECTED'
