"""empty message

Revision ID: d788b4dd17aa
Revises: bb9e53efe1f0
Create Date: 2019-01-12 20:24:25.024750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd788b4dd17aa'
down_revision = 'bb9e53efe1f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_article_id'), 'article', ['id'], unique=False)
    op.create_index(op.f('ix_article_source_id'), 'article', ['source_id'], unique=False)
    op.create_index(op.f('ix_cookie_id'), 'cookie', ['id'], unique=False)
    op.create_index(op.f('ix_cookie_source_id'), 'cookie', ['source_id'], unique=False)
    op.create_index(op.f('ix_country_id'), 'country', ['id'], unique=False)
    op.create_index(op.f('ix_source_country_id'), 'source', ['country_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_source_country_id'), table_name='source')
    op.drop_index(op.f('ix_country_id'), table_name='country')
    op.drop_index(op.f('ix_cookie_source_id'), table_name='cookie')
    op.drop_index(op.f('ix_cookie_id'), table_name='cookie')
    op.drop_index(op.f('ix_article_source_id'), table_name='article')
    op.drop_index(op.f('ix_article_id'), table_name='article')
    # ### end Alembic commands ###
