export const LOGIN_USER_SENT = 'LOGIN_USER_SENT'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_REJECTED = 'LOGIN_USER_REJECTED'

export const REGISTER_USER_SENT = 'REGISTER_USER_SENT'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_REJECTED = 'REGISTER_USER_REJECTED'

export const FETCH_EMAIL_DATA_SENT = 'FETCH_EMAIL_DATA_SENT'
export const FETCH_EMAIL_DATA_SUCCESS = 'FETCH_EMAIL_DATA_SUCCESS'
export const FETCH_EMAIL_DATA_REJECTED = 'FETCH_EMAIL_DATA_REJECTED'

export const FETCH_EMAIL_HISTORY_SENT = 'FETCH_EMAIL_HISTORY_SENT'
export const FETCH_EMAIL_HISTORY_SUCCESS = 'FETCH_EMAIL_HISTORY_SUCCESS'
export const FETCH_EMAIL_HISTORY_REJECTED = 'FETCH_EMAIL_HISTORY_REJECTED'

export const FETCH_EMAIL_TASKS_SENT = 'FETCH_EMAIL_TASKS_SENT'
export const FETCH_EMAIL_TASKS_SUCCESS = 'FETCH_EMAIL_TASKS_SUCCESS'
export const FETCH_EMAIL_TASKS_REJECTED = 'FETCH_EMAIL_TASKS_REJECTED'

export const FETCH_EMAIL_TEMPLATES_SENT = 'FETCH_EMAIL_TEMPLATES_SENT'
export const FETCH_EMAIL_TEMPLATES_SUCCESS = 'FETCH_EMAIL_TEMPLATES_SUCCESS'
export const FETCH_EMAIL_TEMPLATES_REJECTED = 'FETCH_EMAIL_TEMPLATES_REJECTED'

export const SAVE_EMAIL_TEMPLATE_SENT = 'SAVE_EMAIL_TEMPLATE_SENT'
export const SAVE_EMAIL_TEMPLATE_SUCCESS = 'SAVE_EMAIL_TEMPLATE_SUCCESS'
export const SAVE_EMAIL_TEMPLATE_REJECTED = 'SAVE_EMAIL_TEMPLATE_REJECTED'

export const DELETE_EMAIL_TEMPLATE_SENT = 'DELETE_EMAIL_TEMPLATE_SENT'
export const DELETE_EMAIL_TEMPLATE_SUCCESS = 'DELETE_EMAIL_TEMPLATE_SUCCESS'
export const DELETE_EMAIL_TEMPLATE_REJECTED = 'DELETE_EMAIL_TEMPLATE_REJECTED'

export const LOAD_EMAIL_TEMPLATE_SENT = 'LOAD_EMAIL_TEMPLATE_SENT'
export const LOAD_EMAIL_TEMPLATE_SUCCESS = 'LOAD_EMAIL_TEMPLATE_SUCCESS'
export const LOAD_EMAIL_TEMPLATE_REJECTED = 'LOAD_EMAIL_TEMPLATE_REJECTED'